### ISSUE TITLE
PyPi does not include tarballs, and repo does not include version tags

### ISSUE THREAD

**Issue by goanpeca** [zoccoler/napari-metroid#14]
We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. 

As part of this process we create the conda packages on [conda-forge](https://conda-forge.org/) based on either PyPI by

1. relying on the tarballs, but currently no tarballs are available on PyPI
2. The repository does not contain any tags that point to the specific versions. Tags can be used instead of the pypi tarballs.

---

Do you think it would be possible to provide fixes to the above issues? 

Thanks a lot! :)

**Comment by goanpeca** [comment]
Pinging @haesleinhuepf @zoccoler :)

**Comment by zoccoler** [comment]
Hi @goanpeca ,

Could you check if that's fixed now? :)
